"""端口协议：用例层依赖的抽象接口（依赖倒置边界）。

pywezterm 的 Pty/Terminal 与 PtyPort/TerminalPort 结构匹配，无需再包
wrapper 类；Mux 门面（MuxPanel）即驱动层实现，用例层（frame/input）
只依赖 MuxPanelPort/ConsolePort/ClipboardPort/OutputSink。
"""

from typing import List, Protocol, Tuple, Union

from leaf.domain.events import KeyEvent, MouseEvent, ResizeEvent

InputEvent = Union[KeyEvent, MouseEvent, ResizeEvent]


class ConsolePort(Protocol):
    """控制台端口：输入事件流与宿主终端尺寸控制"""

    def wait_input(self, ms: int) -> bool: ...
    def read_inputs(self) -> List[InputEvent]: ...
    def size(self) -> Tuple[int, int]: ...
    def restore(self) -> None: ...


class MuxPanelPort(Protocol):
    """Mux 门面端口：用例层（frame/input）依赖的共享复用器抽象。

    一个 Mux 持有多个 pane + 分隔线 + 状态栏，统一完成增量渲染合成与事件路由。
    """

    def pane_count(self) -> int: ...
    def focused(self) -> int: ...
    def set_focus(self, pane_id: int) -> None: ...
    def split_col(self) -> int: ...
    def set_split_col(self, split_col) -> None: ...
    def resize(self, cols: int, rows: int) -> None: ...
    def pane_sizes(self): ...
    def name(self, pane_id: int) -> str: ...
    def key_down(self, key: str, mods: int) -> bytes: ...
    def key_up(self, key: str, mods: int) -> bytes: ...
    def mouse(self, x: int, y: int, kind: str, button: str, mods: int) -> bytes: ...
    def pane_at(self, x: int, y: int): ...
    def pane_is_mouse_grabbed(self, pane_id: int) -> bool: ...
    def scroll_pane(self, pane_id: int, delta: int) -> None: ...
    def scroll_to_bottom(self) -> None: ...
    def set_status(self, text: str) -> None: ...
    def render(self): ...
    def cursor_seq(self, row: int, col: int, visible: bool) -> str: ...
    def all_eof(self) -> bool: ...
    def close(self) -> None: ...
    # ---- 选区：整屏坐标入口，绑定层命中/换算 ----
    def pane_selection_set(self, pane_id: int, anchor_x: int, anchor_y: int,
                           end_x: int, end_y: int) -> None: ...
    def pane_selection_select_word(self, pane_id: int, x: int, y: int) -> None: ...
    def pane_selection_select_line(self, pane_id: int, x: int, y: int) -> None: ...
    def pane_selection_text(self, pane_id: int) -> str: ...
    def pane_selection_active(self, pane_id: int) -> bool: ...
    def pane_selection_clear(self, pane_id: int) -> None: ...
    def set_focus_selection_callback(self, callback) -> None: ...
    def send_paste(self, text: str) -> None: ...


class ClipboardPort(Protocol):
    """系统剪贴板端口（选区复制 / 宿主粘贴）"""

    def read(self) -> str: ...
    def write(self, text: str) -> None: ...


class OutputSink(Protocol):
    """渲染输出端口：整帧/光标序列写出"""

    def write(self, s: str) -> None: ...
    def flush(self) -> None: ...
